name: Check a pull request (lint)

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      
      - name: Install
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn run build