name: Check a pull request (lint)

on:
  pull_request:
    branches: [master]

jobs:
  lint_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Set up Node js
        uses: actions/setup-node@v2
        with:
          node-version: '14.14.0'

      - name: Install
        run: yarn

      - name: Lint
        run: yarn lint
      
      - name: Jest (unit test)
        run: yarn jest

      - name: Cypress (integration test)
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start      
      