name: Check new code and deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Install
        uses: |
          yarn
      - name: Lint
        uses: |
          yarn lint
      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        uses: |
          yarn run deploy
